## Site metadata ##

title: TILT
description: Transparency Information Language and Toolkit

### Built settings ###

url: "https://transparency-information-language.github.io"
baseurl: "/meta/"

github_username: Transparency-Information-Language/meta

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one